# Generated by Django 5.1.1 on 2024-09-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.IntegerField(default=0)),
                ('Description', models.CharField(default='', max_length=200)),
                ('Image', models.ImageField(upload_to='Upload/products/')),
            ],
        ),
    ]
